name: Trigger auto deployment for container-app-sop5l2evf6jws

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/container-app-sop5l2evf6jws-AutoDeployTrigger-fa65aa3b-557a-47d5-8bab-b4f39305568c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSOP5L2EVF6JWS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSOP5L2EVF6JWS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSOP5L2EVF6JWS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: containerregistrysop5l2evf6jws.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPSOP5L2EVF6JWS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSOP5L2EVF6JWS_REGISTRY_PASSWORD }}
          containerAppName: container-app-sop5l2evf6jws
          resourceGroup: azureflaskmysqlflexibleappservice8a34
          imageToBuild: containerregistrysop5l2evf6jws.azurecr.io/container-app-sop5l2evf6jws:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


